import {chromium} from 'playwright';
import {execFileSync} from 'node:child_process';
import {mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
const output = process.env.PLAYGROUND_EVIDENCE;
const tools = process.env.PLAYGROUND_WASM_TOOLS;
if (!output || !tools) throw Error('PLAYGROUND_EVIDENCE and PLAYGROUND_WASM_TOOLS are required');
mkdirSync(`${output}/fixtures`, {recursive:true});
for (const name of ['monotonic-clock','clock-subscription','poll','filesystem','network','javascript','memory-high','memory-unbounded','core-start-loop','repeated-memory-instance']) execFileSync('node', [`${tools}/run-wasm-tools.mjs`, `${tools}/wasm-tools.wasm`, 'parse', fileURLToPath(new URL(`fixtures/${name}.wat`, import.meta.url)), '-o', `${output}/fixtures/${name}.wasm`]);
writeFileSync(`${output}/fixtures/malformed.wasm`, new Uint8Array([0,97,115,109,13,0,1]));
const browser=await chromium.launch({headless:true});const cases=[],errors=[],requests=[];
try{const page=await browser.newPage();page.on('pageerror',e=>errors.push(String(e)));page.on('request',r=>requests.push({url:r.url(),method:r.method(),body:r.postData()}));await page.goto(process.env.PLAYGROUND_URL ?? 'http://127.0.0.1:5173/playground/');
const hello=await page.evaluate(async()=>{const{PlaygroundPipeline}=await import(new URL('src/pipeline.ts', location.href).href);const events=[];const pipeline=new PlaygroundPipeline(e=>events.push(e));globalThis.phase6={pipeline,events,sequence:1};const snapshot={requestId:1,revision:1,recipeId:'hello',source:'using System; Console.WriteLine(42);'};const compilation=await pipeline.compile(snapshot);if(!compilation.success)throw Error(JSON.stringify(compilation));globalThis.phase6.hello=compilation;const run=await pipeline.run(compilation,snapshot);return{compilation:{...compilation,component:Array.from(compilation.component)},run,events}});if(!hello.run.success||hello.run.stdout!=='42\n')throw Error(JSON.stringify(hello));writeFileSync(`${output}/hello.wasm`,Buffer.from(hello.compilation.component));hello.compilation.component={bytes:hello.compilation.component.length};cases.push({name:'hello',...hello});writeFileSync(`${output}/partial.json`,JSON.stringify({cases,errors},null,2));console.log('hello PASS');
const clockRun=await page.evaluate(async bytes=>globalThis.phase6.pipeline.run({component:new Uint8Array(bytes)},{requestId:++globalThis.phase6.sequence,revision:1,recipeId:'hello',source:''}),Array.from(readFileSync(`${output}/fixtures/monotonic-clock.wasm`)));if(!clockRun.success||clockRun.exitCode!==0)throw Error(JSON.stringify(clockRun));cases.push({name:'monotonic-clock',run:clockRun});console.log('monotonic-clock PASS');
const subscription=await page.evaluate(async bytes=>globalThis.phase6.pipeline.run({component:new Uint8Array(bytes)},{requestId:++globalThis.phase6.sequence,revision:1,recipeId:'hello',source:''}),Array.from(readFileSync(`${output}/fixtures/clock-subscription.wasm`)));if(!subscription.success||subscription.exitCode!==0)throw Error(JSON.stringify(subscription));cases.push({name:'clock-subscription',run:subscription});console.log('clock-subscription PASS');
for(const [name, expected] of Object.entries({poll:"undefined instance import 'attack'",filesystem:"undefined instance import 'attack'",network:'Unsupported guest import',javascript:'Unsupported guest import',malformed:'failed to extract', 'memory-high':'Guest memory limit exceeded', 'memory-unbounded':'Guest memory requires an explicit', 'core-start-loop':'Guest execution time limit exceeded', 'repeated-memory-instance':'Guest memory limit exceeded'})){const bytes=Array.from(readFileSync(`${output}/fixtures/${name}.wasm`));const run=await page.evaluate(async({bytes})=>{const {pipeline}=globalThis.phase6;return await pipeline.run({component:new Uint8Array(bytes)}, {requestId:++globalThis.phase6.sequence,revision:1,recipeId:'hello',source:''})},{bytes});if(run.success||!run.error?.includes(expected))throw Error(`${name} denial mismatch: ${JSON.stringify(run)}`);cases.push({name,run});console.log(name,run.error);const recovery=await page.evaluate(async()=>globalThis.phase6.pipeline.run(globalThis.phase6.hello,{requestId:++globalThis.phase6.sequence,revision:1,recipeId:'hello',source:''}));if(!recovery.success||recovery.stdout!=='42\n')throw Error('Recovery failed');cases.push({name:`${name}-recovery`,run:recovery});writeFileSync(`${output}/partial.json`,JSON.stringify({cases,errors},null,2));}
writeFileSync(`${output}/results.json`,JSON.stringify({passed:true,browser:browser.version(),cases,errors,requests},null,2));if(errors.length)throw Error(errors.join('\n'));console.log('PASS actual pipeline/CSP/memory/import denial/malformed/recovery');
}finally{await browser.close()}
